#!/bin/bash

bpd='20230405'
CT='8'
sleep_time=1
URL="http://uklvadhdp011a.pi.dev.net:8089/eod/${bpd}/status"
DATA='{"country":"GB","branch":"02"}'

while true; do
    RESPONSE=$(curl --silent --location --request GET "$URL" \
        --header 'Content-Type: application/json' \
        --data-raw "$DATA")

    echo "RESPONSE: $RESPONSE"

    EOD_status=$(echo "$RESPONSE" | jq -r '.eodStatus')

    if [[ "$EOD_status" == "COMPLETED" ]]; then
        echo "Success"
        exit 0
    elif [[ "$EOD_status" != "PENDING" ]]; then
        echo "Unexpected status: $EOD_status"
        exit 1
    fi

    sleep "$sleep_time"
done
